version: '3'

services:
  chrome:
    image: selenium/node-chrome:4.20.0-20240425
    shm_size: 1gb
    container_name: selenium-chrome
    depends_on:
      - selenium-hub
    environment:
      - SE_VNC_NO_PASSWORD=1
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  edge:
    image: selenium/node-edge:4.20.0-20240425
    shm_size: 1gb
    container_name: selenium-edge
    depends_on:
      - selenium-hub
    environment:
      - SE_VNC_NO_PASSWORD=1
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  firefox:
    image: selenium/node-firefox:4.20.0-20240425
    shm_size: 1gb
    container_name: selenium-firefox
    depends_on:
      - selenium-hub
    environment:
      - SE_VNC_NO_PASSWORD=1
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  selenium-hub:
    image: selenium/hub:4.20.0-20240425
    container_name: selenium-hub
    env_file:
      - all.env
    ports:
      - "4442:4442"
      - "4443:4443"
      - ${port_selenium_grid}:4444

  allure:
    image: "frankescobar/allure-docker-service"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 1
      KEEP_HISTORY: 1
    ports:
      - "5050:5050"
    volumes:
      - ${PWD}/allure-results:/app/allure-results
      - ${PWD}/allure-reports:/app/default-reports

  allure-ui:
    image: "frankescobar/allure-docker-service-ui"
    environment:
      ALLURE_DOCKER_PUBLIC_API_URL: "http://localhost:5050"
      ALLURE_DOCKER_PUBLIC_API_URL_PREFIX: ""
    ports:
      - "5252:5252"

  pytest:
    build: .
    container_name: pytest
    command: ./wait-for-it.sh   selenium-hub:${port_selenium_grid} -- pytest -sv
    env_file:
      - all.env
    volumes:
      - .:/usr/src/app
    depends_on:
      - selenium-hub

