version: '3'

services:
  chrome:
    image: selenium/node-chrome:4.20.0-20240425
    shm_size: 1gb
    depends_on:
      - selenium-hub
    environment:
      - SE_VNC_NO_PASSWORD=1
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  edge:
    image: selenium/node-edge:4.20.0-20240425
    shm_size: 1gb
    depends_on:
      - selenium-hub
    environment:
      - SE_VNC_NO_PASSWORD=1
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  firefox:
    image: selenium/node-firefox:4.20.0-20240425
    shm_size: 1gb
    depends_on:
      - selenium-hub
    environment:
      - SE_VNC_NO_PASSWORD=1
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  selenium-hub:
    image: selenium/hub:4.20.0-20240425
    container_name: selenium-hub
    env_file:
      - .env
    ports:
      - "4442:4442"
      - "4443:4443"
      - ${port_selenium_grid}:4444
